# metadata
run_name: 'map_wide'
# characteristic number for map
perf_num: 6

#map_name: 'Spielberg'
#map_name: 'example'
#map_name: 'MoscowRaceway'
map_name: 'Catalunya'

# map paths
#map_path: '../maps/Spielberg/Spielberg_map'
#map_path: '../maps/example/example_map'
#map_path: '../maps/MoscowRaceway/MoscowRaceway_map'
map_path: '../maps/Catalunya/Catalunya_map'
map_ext: '.png'

# starting pose for map

# Spielberg
#sx: 0.0
#sy: -0.84
#stheta: 3.40

# example
#sx: 0.7
#sy: 0.0
#stheta: 1.37079632679

# MoscowRaceway
#sx: 0.8232663
#sy: 0.0065730
#stheta: 1.4645504

# Catalunya
sx: 0.5549085
sy: -0.6243834
stheta: 4.1367500

# raceline path and indices
#wpt_path: '../maps/Spielberg/Spielberg_raceline.csv'
#wpt_path: '../maps/example/example_raceline.csv'
#wpt_path: '../maps/MoscowRaceway/MoscowRaceway_raceline.csv'
wpt_path: '../maps/Catalunya/Catalunya_raceline.csv'

wpt_delim: ';'
wpt_rowskip: 3
wpt_xind: 1
wpt_yind: 2
wpt_thind: 3
wpt_vind: 5

# varied params bound
# physical params
mass_min: 3.0
mass_max: 4.0
lf_min: 0.147
lf_max: 0.170
# controller params
tlad_min: 0.2
tlad_max: 5.
vgain_min: 0.5
vgain_max: 1.5

# computation budget (can think of it as gen_num times pop_size)
popsize: 100
budget: 1000

# optimization method
optim_method: 'CMA'

# seed
seed: 12345
